apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 715841356514.dkr.ecr.eu-north-1.amazonaws.com/flask-docker-repo:latest
        ports:
        - containerPort: 5000
